import Link from "next/link";
import { ArrowRight, Building2, Gem, ShieldCheck } from "lucide-react";
import { ProjectCard } from "@/components/project-card";
import { SectionHeading } from "@/components/section-heading";
import { ContactCta } from "@/components/site-shell";
import { StatCard } from "@/components/stat-card";
import { projectFacts, site } from "@/lib/site";

const stats = [[projectFacts.totalApartments, "apartman"], [projectFacts.grossArea, "bruto"], [projectFacts.marketArea, "tržišna površina"], ["21", "parking mesto"]];
const trust = [[ShieldCheck, "Kvalitet gradnje", "Demit fasada, PVC stolarija sa roletnama, aluminijumski ulaz i kvalitetna završna obrada."], [Building2, "Savremena arhitektura", "Ravne linije, kubusi, imitacija kamena i drveta, pastelna fasada uklopljena u ambijent Vrdnika."], [Gem, "Poverenje i transparentnost", "Jasni projektni podaci, dokumentacija i prodajna komunikacija za kupce i investitore."]];

export default function Home() {
  const schema = { "@context": "https://schema.org", "@type": "RealEstateAgent", name: site.name, url: site.url, email: site.email, address: site.location };
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <section className="relative overflow-hidden bg-forest-950 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_20%,rgba(201,162,39,.25),transparent_28%),linear-gradient(135deg,rgba(0,43,38,.82),rgba(0,60,53,.95)),url('/renders/hero-placeholder.svg')] bg-cover bg-center" /><div className="relative mx-auto grid min-h-[760px] max-w-7xl items-center gap-10 px-5 py-24 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div><p className="mb-5 inline-flex rounded-full border border-gold-300/40 px-4 py-2 text-sm text-gold-300">{projectFacts.location}</p><h1 className="max-w-4xl text-5xl font-semibold tracking-tight md:text-7xl">Forest Glade Apart Hotel</h1><p className="mt-6 max-w-2xl text-xl leading-8 text-mist-100">Premium apartmani u Vrdniku, na obroncima Fruške Gore.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><Link href="/projekti" className="rounded-full bg-gold-300 px-7 py-4 font-semibold text-forest-950">Pogledaj projekte</Link><Link href="/kontakt" className="inline-flex items-center gap-2 rounded-full border border-white/25 px-7 py-4 font-semibold">Kontaktirajte nas <ArrowRight size={18}/></Link></div></div><div className="grid gap-4 sm:grid-cols-2">{stats.map(([value, label]) => <StatCard key={label} value={value} label={label} />)}</div></div></section>
    <section className="bg-ivory-100 px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1fr_.55fr] lg:items-stretch"><div className="rounded-[2rem] bg-white p-8 shadow-sm md:p-12"><p className="text-xs font-semibold uppercase tracking-[0.35em] text-gold-500">Forest Glade d.o.o</p><h2 className="mt-4 text-3xl font-semibold leading-tight md:text-5xl">Savremeni apart-hotel koncept za kupce i investitore koji traže dugoročnu vrednost.</h2><p className="mt-6 text-lg leading-8 text-stone-600">Forest Glade d.o.o razvija savremeni apart-hotel koncept u Vrdniku, sa fokusom na kvalitet gradnje, funkcionalne apartmane i premium prezentaciju za kupce i investitore.</p></div><div className="rounded-[2rem] bg-gold-300 p-8 text-forest-950 md:p-10"><p className="text-sm font-semibold uppercase tracking-[0.25em]">Ključni podaci</p><p className="mt-8 text-4xl font-semibold">{projectFacts.totalApartments}</p><p className="mt-2 text-lg">apartman u objektu spratnosti {projectFacts.floors}.</p></div></div></section>
    <section className="bg-white px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Projekti" title="Najnovije iz Forest Glade portfolija" /><div className="mt-10 grid gap-6 md:grid-cols-3"><ProjectCard featured title="Forest Glade Apart Hotel" status="Aktuelni projekat" description="Premium apart-hotel u Vrdniku sa funkcionalnim apartmanima, parkingom i savremenom materijalizacijom." href="/projekti" facts={[projectFacts.location, `${projectFacts.totalApartments} apartman`, projectFacts.marketArea]} /><ProjectCard title="Budući projekti" status="U pripremi" description="Planiranje narednih razvojnih koraka bez navođenja lokacija dok ne budu zvanično potvrđene." /><ProjectCard title="Prodajna prezentacija" status="Za kupce" description="Zatražite informacije o dostupnosti, dokumentaciji i terminima prezentacije projekta." /></div></div></section>
    <section className="bg-forest-900 px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHeading light eyebrow="Poverenje" title="Iskustvo, kvalitet i transparentna prezentacija" /><div className="mt-10 grid gap-6 md:grid-cols-3">{trust.map(([Icon, title, text]) => { const I = Icon as typeof ShieldCheck; return <article key={title as string} className="rounded-[2rem] border border-white/10 bg-white/10 p-7 text-white"><I className="text-gold-300" /><h3 className="mt-5 text-2xl font-semibold">{title as string}</h3><p className="mt-4 leading-7 text-mist-200">{text as string}</p></article>; })}</div></div></section>
    <ContactCta />
  </main>;
}
