CREATE TYPE "AdminRole" AS ENUM ('OWNER', 'ADMIN', 'SALES', 'EDITOR');
CREATE TYPE "ApartmentStatus" AS ENUM ('AVAILABLE', 'RESERVED', 'SOLD', 'HIDDEN');
CREATE TYPE "MediaType" AS ENUM ('IMAGE', 'VIDEO', 'DOCUMENT', 'FLOOR_PLAN', 'RENDER', 'VIRTUAL_TOUR');
CREATE TYPE "MediaPlacement" AS ENUM ('HOME_HERO', 'PROJECT_GALLERY', 'APARTMENT_GALLERY', 'APARTMENT_PLAN', 'FLOOR_PLAN', 'EXTERIOR', 'INTERIOR', 'VIRTUAL_TOUR', 'DOCUMENTATION');
CREATE TYPE "LeadStatus" AS ENUM ('NEW', 'CONTACTED', 'QUALIFIED', 'NOT_INTERESTED', 'CLOSED', 'ARCHIVED');
CREATE TYPE "AuditAction" AS ENUM ('LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'ARCHIVE', 'UPLOAD', 'PUBLISH', 'UNPUBLISH');
ALTER TABLE "Lead" ADD COLUMN "status" "LeadStatus" NOT NULL DEFAULT 'NEW', ADD COLUMN "note" TEXT, ADD COLUMN "assignedToId" TEXT, ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX "Lead_status_idx" ON "Lead"("status");
CREATE INDEX "Lead_createdAt_idx" ON "Lead"("createdAt");
CREATE TABLE "AdminUser" ("id" TEXT NOT NULL,"email" TEXT NOT NULL,"name" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"role" "AdminRole" NOT NULL DEFAULT 'EDITOR',"isActive" BOOLEAN NOT NULL DEFAULT true,"lastLoginAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "AdminUser_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "AdminUser_email_key" ON "AdminUser"("email");
CREATE TABLE "AdminSession" ("id" TEXT NOT NULL,"tokenHash" TEXT NOT NULL,"adminId" TEXT NOT NULL,"ipAddress" TEXT,"userAgent" TEXT,"expiresAt" TIMESTAMP(3) NOT NULL,"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AdminSession_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "AdminSession_tokenHash_key" ON "AdminSession"("tokenHash");
CREATE INDEX "AdminSession_adminId_idx" ON "AdminSession"("adminId");
CREATE INDEX "AdminSession_expiresAt_idx" ON "AdminSession"("expiresAt");
CREATE TABLE "Apartment" ("id" TEXT NOT NULL,"code" TEXT NOT NULL,"slug" TEXT NOT NULL,"floor" TEXT NOT NULL,"officialType" TEXT NOT NULL,"marketArea" DECIMAL(8,2) NOT NULL,"status" "ApartmentStatus" NOT NULL DEFAULT 'AVAILABLE',"price" DECIMAL(12,2),"priceNote" TEXT,"shortDescription" TEXT,"description" TEXT,"seoTitle" TEXT,"seoDescription" TEXT,"isPublished" BOOLEAN NOT NULL DEFAULT true,"sourceLocked" BOOLEAN NOT NULL DEFAULT true,"sortOrder" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Apartment_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Apartment_code_key" ON "Apartment"("code");
CREATE UNIQUE INDEX "Apartment_slug_key" ON "Apartment"("slug");
CREATE TABLE "MediaAsset" ("id" TEXT NOT NULL,"type" "MediaType" NOT NULL,"placement" "MediaPlacement" NOT NULL,"title" TEXT NOT NULL,"alt" TEXT,"caption" TEXT,"apartmentId" TEXT,"cloudinaryPublicId" TEXT NOT NULL,"secureUrl" TEXT NOT NULL,"thumbnailUrl" TEXT,"format" TEXT,"width" INTEGER,"height" INTEGER,"durationSeconds" INTEGER,"bytes" INTEGER,"sortOrder" INTEGER NOT NULL DEFAULT 0,"isPublished" BOOLEAN NOT NULL DEFAULT false,"createdById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "MediaAsset_pkey" PRIMARY KEY ("id"));
CREATE INDEX "MediaAsset_apartmentId_idx" ON "MediaAsset"("apartmentId");
CREATE INDEX "MediaAsset_placement_idx" ON "MediaAsset"("placement");
CREATE INDEX "MediaAsset_isPublished_idx" ON "MediaAsset"("isPublished");
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL,"adminId" TEXT,"action" "AuditAction" NOT NULL,"entity" TEXT NOT NULL,"entityId" TEXT,"message" TEXT,"beforeJson" JSONB,"afterJson" JSONB,"ipAddress" TEXT,"userAgent" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));
CREATE INDEX "AuditLog_adminId_idx" ON "AuditLog"("adminId");
CREATE INDEX "AuditLog_entity_idx" ON "AuditLog"("entity");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");
CREATE TABLE "SiteSetting" ("id" TEXT NOT NULL,"key" TEXT NOT NULL,"value" JSONB NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "SiteSetting_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "SiteSetting_key_key" ON "SiteSetting"("key");
ALTER TABLE "AdminSession" ADD CONSTRAINT "AdminSession_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "AdminUser"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MediaAsset" ADD CONSTRAINT "MediaAsset_apartmentId_fkey" FOREIGN KEY ("apartmentId") REFERENCES "Apartment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MediaAsset" ADD CONSTRAINT "MediaAsset_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
